### ISSUE TITLE
大哥，您这咋读取文件啊？

### ISSUE THREAD

**Issue by ghost** [moyanj/AList3SDK#1]
大哥，您这咋读取文件啊？
只能操作目录和上传吗，读取是怎么个章程啊

**Comment by moyanj** [comment]
AList.open(路径)方法，返回一个AListFile对象，可以对这个对象进行读(用read或者save方法)([源码](https://github.com/moyanj/AList3SDK/blob/main/alist/file.py))

**Comment by moyanj** [comment]
还有，read方法返回的是字节

**Comment by ghost** [comment]
源码中有个print,能否·优化下，总是打印出无关的信息

**Comment by moyanj** [comment]
更到1.1.1版本就行了
